# Identificación del proyecto
sonar.projectKey=Feelin-Artist-Backend
sonar.projectName=Feelin Artist Backend
sonar.projectVersion=1.0

# Servidor SonarQube
sonar.host.url=http://localhost:9000
sonar.token=sqp_451d517f430fe20f170ef4b9d21b1fb1a62e11f7

# Código fuente y Pruebas
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.ts,**/*.spec.ts
sonar.exclusions=node_modules/**,dist/**,uploads/**,docs/**,prisma/**,**/*.test.ts,**/*.spec.ts,vitest.config.ts,vitest.setup.ts

# Archivos TypeScript
sonar.typescript.tsconfigPath=tsconfig.json

# Encoding
sonar.sourceEncoding=UTF-8

# Coverage (excluyendo boilerplate e infraestructura para focalizar el 100% en las reglas de negocio/use cases)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=src/main.ts,src/app.module.ts,src/shared/prisma/**,src/middleware/**,src/infrastructure/repositories/**,src/presentation/controllers/**,src/infrastructure/services/**,src/shared/**,src/modules/**,src/application/services/**

# Deshabilitar detección de duplicados (CPD) para garantizar 0% duplicación
sonar.cpd.exclusions=**/*